<h1> NUMPY </h1>

In [1]:
"Numpy deals with native array data structures while Python deals with lists"

'Numpy deals with native array data structures while Python deals with lists'

In [2]:
import numpy as np

## Task 1: Creating nd array objects 

### Using np.array() function

#### A. 1-Dimensional Array

In [9]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#### B. 2-Dimensional Array

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Using Numpy Functions

#### A. Using Zeros function

In [20]:
c=np.zeros((3,2)) # Create a 3x2 array  filled with zeros
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
d=np.zeros((3,4))  # Create a 3x4 array  filled with zeros
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### B. Using random function

In [25]:
e=np.random.random(3)
e

array([0.51822264, 0.4383894 , 0.79160708])

#### C. Using full() function

In [27]:
f=np.full((2,2),12) # Create 2x2 array with constant values of 12
f

array([[12, 12],
       [12, 12]])

In [29]:
g=np.full((2,2),12,dtype=np.float32) # Create 2x2 array with constant values of 12
g

array([[12., 12.],
       [12., 12.]], dtype=float32)

## Task 2: Creating a sequence

In [ ]:
"The most common functions are np.arrange() and n.linspace function"

#### Method 1: Using np.arange()

In [ ]:
"The np.arrange syntax: np.arrange(start,end,step)"

### A. Using start,end,step

In [31]:
h=np.arange(0,10,2)
h

array([0, 2, 4, 6, 8])

### B. Using end only

In [33]:
i=np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Method 2: Using np.linspace()

In [ ]:
"The np.linspace syntax: np.linspace(start,end,num_values)"

In [38]:
np.linspace(0,7,7)

array([0.        , 1.16666667, 2.33333333, 3.5       , 4.66666667,
       5.83333333, 7.        ])

## Task 3: Accessing Elements

In [6]:
b[1,2] # Second row and Third column of Array 'b'

7

## Task 4: Array Parameters

### A. Dimensions of Array

In [14]:
"Displays the dimensions of array e.g., 1-Dimensional, 2-Dimensional Array"

'Displays the dimensions of array e.g., 1-Dimensional, 2-Dimensional Array'

In [10]:
a.ndim

1

In [11]:
b.ndim

2

### B. Number of Elements

In [15]:
"Returns the total number of elements in the given array"

'Returns the total number of elements in the given array'

In [12]:
a.size

4

In [13]:
b.size

8

### C. Type of Array

In [ ]:
"Returns the element type of the Array"

In [16]:
type(a)

numpy.ndarray

In [17]:
type(b)

numpy.ndarray

### D. Shape of Array

In [39]:
arange_arr=np.arange(10)
arange_arr.shape

(10,)

In [46]:
arange_arr.shape[0]>100

False